name: Salesforce CI/CD

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a recent Node.js version

      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --location=global

      - name: write config files
        run: | 
          printf '%s' '${{ secrets.SFDX_AUTH_URL }}' > auth_url
          cat auth_url 

      - name: Authenticate to Salesforce Org
        run: sf org login sfdx-url --sfdx-url-file auth_url --alias myorg
        
      - name: Display org details (optional)
        run: sf org display -o myorg

      - name: Deploy to Salesforce Org
        run: sf project deploy start --manifest ./manifest/package.xml --target-org myorg --wait 30

      - name: Run Apex Tests
        run: sf apex run test --code-coverage --result-format human --wait 10 --target-org myorg

      - name: Post deployment verification (optional)
        # Add steps here to verify the deployment, e.g., running post-deploy scripts.
        run: echo "Deployment complete."